// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// rotary_enc //
// ---------- //

#define rotary_enc_wrap_target 0
#define rotary_enc_wrap 4

static const uint16_t rotary_enc_program_instructions[] = {
            //     .wrap_target
    0x2020, //  0: wait   0 pin, 0                   
    0x20a0, //  1: wait   1 pin, 0                   
    0x4002, //  2: in     pins, 2                    
    0x8020, //  3: push   block                      
    0x0000, //  4: jmp    0                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program rotary_enc_program = {
    .instructions = rotary_enc_program_instructions,
    .length = 5,
    .origin = -1,
};

static inline pio_sm_config rotary_enc_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + rotary_enc_wrap_target, offset + rotary_enc_wrap);
    return c;
}

static inline void rotary_enc_program_init(PIO pio, uint sm, uint offset, uint pin_a, uint pin_b) {
    pio_sm_set_enabled(pio, sm, false);
    pio_gpio_init(pio, pin_a);
    pio_gpio_init(pio, pin_b);
    gpio_pull_up(pin_a);
    gpio_pull_up(pin_b);
    pio_sm_set_consecutive_pindirs(pio, sm, pin_a, 2, false);
    pio_sm_config c = rotary_enc_program_get_default_config(offset);
    sm_config_set_in_pins(&c, pin_a);   
    sm_config_set_jmp_pin(&c, pin_a);
    sm_config_set_in_shift(&c, false, false, 0);
    sm_config_set_clkdiv(&c, 150.0f);  // Honestly idk what the clock is but im assuming its 150MHz, which is I divide by 150. 
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif
